# 회귀 및 분류 연습

In [1]:
from sklearn.datasets import load_iris

In [2]:
iris = load_iris()

In [3]:
x = iris.data
y = iris.target

In [4]:
x.shape, y.shape

((150, 4), (150,))

In [5]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [6]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [7]:
# One-Hot Encoding
from tensorflow.keras.utils import to_categorical

In [8]:
y = to_categorical(y, 3)

In [9]:
x.shape, y.shape

((150, 4), (150, 3))

# Sequential API

In [10]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [11]:
keras.backend.clear_session()

model = keras.models.Sequential()

model.add(keras.layers.Input(shape = (4,)))
# 이중분류 : sigmoid
# 다중분류 : softmax
# 회귀 : x
model.add(keras.layers.Dense(3, activation = 'softmax'))

# 이중분류 : 'binary_crossentropy'
# 다중분류 : 'categorical_crossentropy'
# 회귀 : 'mse'
model.compile(loss = 'categorical_crossentropy',
             optimizer = 'adam',
             metrics = ['accuracy'])

model.fit(x, y, epochs = 10, verbose = 1)

pred = model.predict(x)

print(y[:5])
print(pred[:5].reshape(-1))

Epoch 1/10
5/5 [==============================] - 0s 2ms/step - loss: 1.5573 - accuracy: 0.3333
Epoch 2/10
5/5 [==============================] - 0s 2ms/step - loss: 1.5045 - accuracy: 0.3333
Epoch 3/10
5/5 [==============================] - 0s 2ms/step - loss: 1.4532 - accuracy: 0.3333
Epoch 4/10
5/5 [==============================] - 0s 1ms/step - loss: 1.4047 - accuracy: 0.3333
Epoch 5/10
5/5 [==============================] - 0s 2ms/step - loss: 1.3548 - accuracy: 0.3333
Epoch 6/10
5/5 [==============================] - 0s 2ms/step - loss: 1.3122 - accuracy: 0.3333
Epoch 7/10
5/5 [==============================] - 0s 2ms/step - loss: 1.2663 - accuracy: 0.3333
Epoch 8/10
5/5 [==============================] - 0s 2ms/step - loss: 1.2266 - accuracy: 0.3333
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 1.1881 - accuracy: 0.3333
Epoch 10/10
5/5 [==============================] - 0s 2ms/step
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
[0.19297685 

# Functional API

In [12]:
keras.backend.clear_session()

input = keras.layers.Input(shape = (4,))
output = keras.layers.Dense(3, activation = 'softmax')(input)

model = keras.models.Model(input, output)

model.compile(loss = 'categorical_crossentropy',
             optimizer = 'adam',
             metrics = ['accuracy'])

model.fit(x, y, epochs = 10, verbose = 1)

pred = model.predict(x)

print(y[:5])
print(pred[:5].reshape(-1))

Epoch 1/10
5/5 [==============================] - 0s 2ms/step - loss: 1.4361 - accuracy: 0.3333
Epoch 2/10
5/5 [==============================] - 0s 2ms/step - loss: 1.3703 - accuracy: 0.3333
Epoch 3/10
5/5 [==============================] - 0s 2ms/step - loss: 1.3120 - accuracy: 0.3333
Epoch 4/10
5/5 [==============================] - 0s 2ms/step - loss: 1.2576 - accuracy: 0.3333
Epoch 5/10
5/5 [==============================] - 0s 2ms/step - loss: 1.2092 - accuracy: 0.3400
Epoch 6/10
5/5 [==============================] - 0s 2ms/step - loss: 1.1681 - accuracy: 0.3800
Epoch 7/10
5/5 [==============================] - 0s 2ms/step - loss: 1.1336 - accuracy: 0.3933
Epoch 8/10
5/5 [==============================] - 0s 2ms/step - loss: 1.0995 - accuracy: 0.4600
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 1.0746 - accuracy: 0.5333
Epoch 10/10
5/5 [==============================] - 0s 3ms/step
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
[0.51898646 