In [1]:
from sklearn.datasets import load_iris

In [2]:
iris = load_iris()

In [3]:
x = iris.data
y = iris.target

In [4]:
x.shape, y.shape

((150, 4), (150,))

In [5]:
#####################
# 라이브러리 불러오기
#####################
import tensorflow as tf
from tensorflow import keras
import numpy as np
from tensorflow.keras.utils import to_categorical
from sklearn.model_selection import train_test_split

In [6]:
#################
# train test 분할
#################
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 20160320)

In [7]:
#######################
# 어떤 전처리 작업 필요
# Hint : y.shape
#######################
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

y_train.shape, y_test.shape

((120, 3), (30, 3))

In [8]:
###################
# 모델링 Sequential
###################
keras.backend.clear_session()

model = keras.models.Sequential()

model.add(keras.layers.Input(shape = (4,)))
model.add(keras.layers.Dense(4, activation = 'relu'))
model.add(keras.layers.Dense(4, activation = 'relu'))
model.add(keras.layers.Dense(3, activation = 'softmax'))

model.compile(loss = 'categorical_crossentropy',
             optimizer = 'adam',
             metrics = ['accuracy'])

model.fit(x_train, y_train, epochs = 10, verbose = 1)

pred = model.predict(x_test)
pred = np.where(pred >= 0.5, 1, 0)

print(y_test[:10])
print(pred[:10])

Epoch 1/10
4/4 [==============================] - 0s 3ms/step - loss: 1.6262 - accuracy: 0.3417
Epoch 2/10
4/4 [==============================] - 0s 3ms/step - loss: 1.5863 - accuracy: 0.3417
Epoch 3/10
4/4 [==============================] - 0s 2ms/step - loss: 1.5414 - accuracy: 0.3417
Epoch 4/10
4/4 [==============================] - 0s 2ms/step - loss: 1.5022 - accuracy: 0.3417
Epoch 5/10
4/4 [==============================] - 0s 2ms/step - loss: 1.4662 - accuracy: 0.3417
Epoch 6/10
4/4 [==============================] - 0s 2ms/step - loss: 1.4339 - accuracy: 0.3417
Epoch 7/10
4/4 [==============================] - 0s 2ms/step - loss: 1.4048 - accuracy: 0.3417
Epoch 8/10
4/4 [==============================] - 0s 3ms/step - loss: 1.3752 - accuracy: 0.3417
Epoch 9/10
4/4 [==============================] - 0s 2ms/step - loss: 1.3488 - accuracy: 0.3417
Epoch 10/10
1/1 [==============================] - 0s 85ms/step
[[0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]


In [9]:
###################
# 모델링 Functional
###################
keras.backend.clear_session()

input = keras.layers.Input(shape = (4,))
hidden1 = keras.layers.Dense(4, activation = 'relu')(input)
hidden2 = keras.layers.Dense(4, activation = 'relu')(hidden1)
output = keras.layers.Dense(3, activation = 'softmax')(hidden2)

model = keras.models.Model(input, output)

model.compile(loss = 'categorical_crossentropy',
             optimizer = 'adam',
             metrics = ['accuracy'])

model.fit(x_train, y_train, epochs = 10, verbose = 1)

pred = model.predict(x_test)
pred = np.where(pred >= 0.5, 1, 0)

print(y_test[:10])
print(pred[:10])

Epoch 1/10
4/4 [==============================] - 0s 2ms/step - loss: 1.5426 - accuracy: 0.3417
Epoch 2/10
4/4 [==============================] - 0s 2ms/step - loss: 1.5105 - accuracy: 0.3417
Epoch 3/10
4/4 [==============================] - 0s 2ms/step - loss: 1.4820 - accuracy: 0.3417
Epoch 4/10
4/4 [==============================] - 0s 2ms/step - loss: 1.4527 - accuracy: 0.3417
Epoch 5/10
4/4 [==============================] - 0s 2ms/step - loss: 1.4293 - accuracy: 0.3417
Epoch 6/10
4/4 [==============================] - 0s 3ms/step - loss: 1.4050 - accuracy: 0.3417
Epoch 7/10
4/4 [==============================] - 0s 3ms/step - loss: 1.3782 - accuracy: 0.3417
Epoch 8/10
4/4 [==============================] - 0s 2ms/step - loss: 1.3572 - accuracy: 0.3417
Epoch 9/10
4/4 [==============================] - 0s 3ms/step - loss: 1.3374 - accuracy: 0.3417
Epoch 10/10
1/1 [==============================] - 0s 54ms/step
[[0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
